language: node_js
node_js: '0.10'
sudo: false
addons:
  ssh_known_hosts: ssh-sudweb.alwaysdata.net
  apt_packages:
  - graphicsmagick
before_install:
- openssl aes-256-cbc -K $encrypted_945f3b1f3b36_key -iv $encrypted_945f3b1f3b36_iv -in id_rsa.enc -out $TRAVIS_BUILD_DIR/id_rsa -d
- npm install -g grunt-cli
- bundle install
after_success:
- if [ $TRAVIS_BRANCH !== 'master' ]; then exit 0; fi
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/id_rsa
- ssh-add $TRAVIS_BUILD_DIR/id_rsa
- npm run deploy-prod
- ssh sudweb@ssh-sudweb.alwaysdata.net 'cd www/2014 && git pull origin gh-pages'
